UmbracoDemo/Models/ContactUsModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace UmbracoDemo.Models
{
    public class ContactUsModel
    {
        public string Name { get; set; }

        public string Email { get; set; }

        public string Phone { get; set; }

        public string Message { get; set; }
    }
}

UmbracoDemo/Controllers/ContactSurfaceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Mail;
using System.Web;
using System.Web.Mvc;
using Umbraco.Web.Mvc;
using UmbracoDemo.Models;

namespace UmbracoDemo.Controllers
{
    public class ContactSurfaceController : SurfaceController
    {
        // GET: ContactSurface
        public ActionResult GetContactUs()
        {
            return View("ContactUs",new ContactUsModel());
        }

        public ActionResult PostContactDetails(ContactUsModel model)
        {

            MailMessage email = new MailMessage(model.Email, "manohar.ra@gmail.com");
            email.Subject = "Contact Form Request";
            email.Body = model.Message;

            try
            {
                //Connect to SMTP credentials set in web.config
                SmtpClient smtp = new SmtpClient();

                //Try & send the email with the SMTP settings
                smtp.Send(email);
            }
            catch (Exception ex)
            {
                //Throw an exception if there is a problem sending the email
                throw ex;
            }

            //Update success flag (in a TempData key)
            TempData["IsSuccessful"] = true;

            //All done - lets redirect to the current page & show our thanks/success message
            return RedirectToCurrentUmbracoPage();
            return RedirectToCurrentUmbracoPage();
        }
    }
}

UmbracoDemo/Views/BlogItem.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage<ContentModels.BlogItem>
@using ContentModels = Umbraco.Web.PublishedContentModels;
@{
	Layout = "Master.cshtml";
}

@{
    var typedMediaPickerSingle = Model.Content.GetPropertyValue<IPublishedContent>("blogBanner");
} 

 <header class="masthead" style="background-image: url('@typedMediaPickerSingle.Url')">
      <div class="container">
        <div class="row">
          <div class="col-lg-8 col-md-10 mx-auto">
            <div class="post-heading">
              <h1>@Umbraco.Field("blogTitle")</h1>
              <h2 class="subheading">@Umbraco.Field("blogTeaser")</h2>
              <span class="meta">Posted on
                <a href="#">@Umbraco.Field("creatorName")</a>
                on @Umbraco.Field("createDate", formatAsDate: true, convertLineBreaks: true)</span>
            </div>
          </div>
        </div>
      </div>
    </header>

    <!-- Post Content -->
    <article>
      <div class="container">
        <div class="row">
          <div class="col-lg-8 col-md-10 mx-auto">
           @Umbraco.Field("blog")
          </div>
        </div>
      </div>
    </article>

UmbracoDemo/Views/BlogPage.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage<ContentModels.BlogPage>
@using ContentModels = Umbraco.Web.PublishedContentModels;
@{
	Layout = "Master.cshtml";
}
@{
    var typedMediaPickerSingle = Model.Content.GetPropertyValue<IPublishedContent>("backgroundImage");
} 

 <header class="masthead" style="background-image: url('@typedMediaPickerSingle.Url')">
      <div class="container">
        <div class="row">
          <div class="col-lg-8 col-md-10 mx-auto">
            <div class="page-heading" style="margin-top: -85px;">
              <h1>Blog Post</h1>
              <span class="subheading">This is a blog page Listing</span>
            </div>
          </div>
        </div>
      </div>
    </header>

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.6.3/css/font-awesome.css">
<div class="row">
   
    @Html.Partial("BlogItem")
   
</div>

UmbracoDemo/Views/Contact.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage<ContentModels.Contact>
@using ContentModels = Umbraco.Web.PublishedContentModels;
@{
	Layout = "Master.cshtml";
}

@{
    var typedMediaPickerSingle = Model.Content.GetPropertyValue<IPublishedContent>("backgroundImage");
} 

 <header class="masthead" style="background-image: url('@typedMediaPickerSingle.Url')">
      <div class="container">
        <div class="row">
          <div class="col-lg-8 col-md-10 mx-auto">
            <div class="page-heading">
              <h1>Contact Me</h1>
              <span class="subheading">Have questions? I have answers (maybe).</span>
            </div>
          </div>
        </div>
      </div>
    </header>

    <!-- Main Content -->
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <p>Want to get in touch with me? Fill out the form below to send me a message and I will try to get back to you within 24 hours!</p>
         
          @Umbraco.RenderMacro("renderUmbracoForm", new {FormGuid="34fd85ae-1cb3-4dc2-8f43-c388e87e8bee", FormTheme="", ExcludeScripts="0"})
       
            @*@Html.Action("GetContactUs", "ContactSurface")*@
    

          
        </div>
      </div>
    </div>

UmbracoDemo/Views/HomePage.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage<ContentModels.HomePage>
@using ContentModels = Umbraco.Web.PublishedContentModels;
@{
	Layout = "Master.cshtml";
}

@{
    var typedMediaPickerSingle = Model.Content.GetPropertyValue<IPublishedContent>("backgroundImage");
} 

 <header class="masthead" style="background-image: url('@typedMediaPickerSingle.Url')">
      <div class="container">
        <div class="row">
          <div class="col-lg-8 col-md-10 mx-auto">
            <div class="site-heading">
              <h1>@Umbraco.Field("bannerText")</h1>
              <span class="subheading">@Umbraco.Field("bannerDescription")</span>
              <a href="#" style="
    font-size: 20px;
    font-weight: 500;
    letter-spacing: 0.1px;
    text-align: center;
    color: #fff;
    border-radius: 2px;
    display: inline-block;
    padding: 8px 20px;
    background-color: #fa5757;
    text-shadow: 2px 2px 27px #000;
">Find a Restaurant</a>
            </div>
          </div>
        </div>
      </div>
    </header>
    
    <div class="row">
        @Html.Partial("BlogItem")
    </div>

UmbracoDemo/Views/MacroPartials/InsertUmbracoFormWithTheme.cshtml
@inherits Umbraco.Web.Macros.PartialViewMacroPage
	
@if (Model.MacroParameters["FormGuid"] != null)
{
    var s = Model.MacroParameters["FormGuid"].ToString();
    var theme = "";
    var includeScripts = true;

    @*
        If a theme is provided as a macro parameter, forms will attempt to use custom theme files
        ex: given the value "test", forms will look up views for the form and fields in a custom directory:

        Form will be rendered with
            /Views/Partials/Forms/Themes/test/form.cshml

        Fields will be rendered with
            /Views/Partials/Forms/Themes/test/FieldType/[fieldtypename].cshtml

        If a file is not available in the custom directory, forms will fallback to the default files in
            /Views/Partials/Forms/Themes/default/
    *@

    if(Model.MacroParameters.ContainsKey("FormTheme"))
    {
        theme = Model.MacroParameters["FormTheme"].ToString();
    }

    if (Model.MacroParameters.ContainsKey("ExcludeScripts"))
    {

        @*
            Inverse the boolean - RenderAction Parameter expects it to be false for exclusion
            But with default value for Macro Paramater boolean/checkbox being false 
            We want to ensure by default we include the scripts next to the form
        *@
        includeScripts = Model.MacroParameters["ExcludeScripts"].ToString() == "0";
    }

    var form = new Guid(s);
    var recordGuid = Guid.Empty;

    if (string.IsNullOrEmpty(Request.QueryString["recordId"]) == false)
    {
        Guid.TryParse(Request.QueryString["recordId"], out recordGuid);
    }

    Html.RenderAction("RenderForm", "UmbracoForms", new {formId = form, recordId = recordGuid, theme = theme, includeScripts = includeScripts,mode = "form" });
}

UmbracoDemo/Views/MacroPartials/RenderUmbracoFormScripts.cshtml
@inherits Umbraco.Web.Macros.PartialViewMacroPage
@using Umbraco.Forms.Web.Controllers

@if (TempData["UmbracoForms"] != null)
{
    foreach (var form in (List<Guid>)TempData["UmbracoForms"])
    {
        Html.RenderAction("Render", "UmbracoForms", new { formId = form, mode = "script"});
    }
}
    

UmbracoDemo/Views/Master.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@{
	Layout = null;
}

@* the fun starts here *@

<!DOCTYPE html>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>@Umbraco.Field("siteName", recursive: true)</title>

    <!-- Bootstrap core CSS -->
    <link href="~/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom fonts for this template -->
    <link href="~/vendor/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>
    <!-- Custom styles for this template -->
    <link href="~/css/clean-blog.min.css" rel="stylesheet">
    <link href="~/css/blog-listing.css" rel="stylesheet">
    
    <script src="http://ajax.aspnetcdn.com/ajax/jQuery/jquery-1.9.1.js"></script>
       <script src="http://ajax.aspnetcdn.com/ajax/jquery.validate/1.13.0/jquery.validate.min.js"></script>
        <script src="http://ajax.aspnetcdn.com/ajax/mvc/5.0/jquery.validate.unobtrusive.min.js"></script>
  </head>
  <body>

    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
      <div class="container">
          
        
        <a class="navbar-brand" href="/Home">@Umbraco.Field("siteName", recursive: true)</a>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          Menu
          <i class="fa fa-bars"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            
                @{
                	var selection = Model.Content.Site().Children()
                						.Where(x => x.IsVisible())
                						.OrderBy("Name");
                }
            
            	@foreach(var item in selection){
            		<li class="nav-item">
            			<a class="nav-link" href="@item.Url">@item.Name</a>
            		</li>
            	}

          </ul>
        </div>
      </div>
    </nav>

  
    

    <!-- Main Content -->
    @RenderBody()
    <hr>

    <!-- Footer -->
    <footer>
      <div class="container">
        <div class="row">
          <div class="col-lg-8 col-md-10 mx-auto">
            <ul class="list-inline text-center">
              <li class="list-inline-item">
                <a href="#">
                  <span class="fa-stack fa-lg">
                    <i class="fa fa-circle fa-stack-2x"></i>
                    <i class="fa fa-twitter fa-stack-1x fa-inverse"></i>
                  </span>
                </a>
              </li>
              <li class="list-inline-item">
                <a href="#">
                  <span class="fa-stack fa-lg">
                    <i class="fa fa-circle fa-stack-2x"></i>
                    <i class="fa fa-facebook fa-stack-1x fa-inverse"></i>
                  </span>
                </a>
              </li>
              <li class="list-inline-item">
                <a href="#">
                  <span class="fa-stack fa-lg">
                    <i class="fa fa-circle fa-stack-2x"></i>
                    <i class="fa fa-github fa-stack-1x fa-inverse"></i>
                  </span>
                </a>
              </li>
            </ul>
            <p class="copyright text-muted">@Umbraco.Field("FooterText", recursive: true)</p>
          </div>
        </div>
      </div>
    </footer>

    <!-- Bootstrap core JavaScript -->
    <script src="~/vendor/jquery/jquery.min.js"></script>
    <script src="~/vendor/popper/popper.min.js"></script>
    <script src="~/vendor/bootstrap/js/bootstrap.min.js"></script>
    
     <!-- Contact Form JavaScript -->
    <script src="~/js/jqBootstrapValidation.js"></script>
    <script src="~/js/contact_me.js"></script>


    <!-- Custom scripts for this template -->
    <script src="~/js/clean-blog.min.js"></script>
    
    
    
    

   
     <!-- Umbraco Forms Dependency -->
     
      
      
     

  </body>

</html>

UmbracoDemo/Views/Partials/BlogItem.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage



@{
	var selection = Model.Content.Site().FirstChild("blogPage").Children("blogItem")
						.Where(x => x.IsVisible());
}

	@foreach(var item in selection){
	<div class="col-sm-3">
        <div class="owl-carousel">
            <div class="post-slide">
                <div class="post-img">
                    
                    
                    @{
                        var typedMediaPickerSingle = item.GetPropertyValue<IPublishedContent>("blogTeaserImage");
                        if (typedMediaPickerSingle != null)
                        {

                            <img class="img-responsive" src="@typedMediaPickerSingle.Url">
                            
                        }
                    }    
   
                    <div class="over-layer">
                        <ul class="post-link">
                            <li>
                                <a href="@item.Url" class="fa fa-link"></a>
                            </li>
                        </ul>
                    </div>
                   
                </div>
                <div class="post-content">
                    <h3 class="post-title">
                        <a href="@item.Url">@item.GetPropertyValue("blogTeaser")</a>
                    </h3>
                    <p class="post-description">@item.GetPropertyValue("BlogshortDescription")</p>
                    <a href="@item.Url" class="read-more">read more..</a>
                </div>
            </div>
        </div>
    </div>
	}

UmbracoDemo/Views/Partials/Forms/Export/csv.cshtml
@model Umbraco.Forms.Web.Models.Backoffice.EntrySearchResultCollection
@foreach (var header in Model.schema)
{<text>"</text>@Html.Raw(header.Name)<text>",</text>}

@foreach (var row in Model.Results)
{
    foreach (var col in row.Fields)
    {<text>"</text>@Html.Raw(col).ToString().Replace(Environment.NewLine, " ")<text>",</text>}

    @Environment.NewLine
}

UmbracoDemo/Views/Partials/Forms/Fieldtypes/FieldType.CheckBox.cshtml
@model Umbraco.Forms.Mvc.Models.FieldViewModel    
<input type="checkbox" name="@Model.Name" id="@Model.Id" 
    @if(Model.Mandatory){<text>  data-val="true" data-val-requiredcb="@Model.RequiredErrorMessage"</text>}
    @if (Model.ContainsValue(true) || Model.ContainsValue("true") || Model.ContainsValue("on"))
    {<text>checked="checked"</text>}       
                                                                                                         
    />

UmbracoDemo/Views/Partials/Forms/Fieldtypes/FieldType.CheckBoxList.cshtml
@model Umbraco.Forms.Mvc.Models.FieldViewModel
@{ var i = 0; }
          
<span class="checkboxlist" id="@Model.Id">
@foreach (Umbraco.Forms.Mvc.Models.PrevalueViewModel pv in Model.PreValues)  
{
    <input type="checkbox" name="@Model.Name" id="@string.Concat(Model.Id,"_",i)" value="@pv.Value" 
    @if (Model.Mandatory) {<text>data-val="true" data-val-requiredlist="@Model.RequiredErrorMessage"</text>}
    @if (Model.ContainsValue(pv.Value)){<text>checked="checked"</text>}/>
    
    <label for="@string.Concat(Model.Id,"_",i)">@pv.Value</label>
    <br />

    i++;
}
</span>

UmbracoDemo/Views/Partials/Forms/Fieldtypes/FieldType.DatePicker.cshtml
@model Umbraco.Forms.Mvc.Models.FieldViewModel        
@{
    string val = string.Empty;
    if (Model.ValueAsObject != null && Model.ValueAsObject != "")
    {
        try
        {
            DateTime d;
            d = (DateTime) Model.ValueAsObject;
            val = d.ToShortDateString();
        }
        catch (Exception ex)
        {
            val = Model.ValueAsObject.ToString();
        }
    }
}

<input type="hidden" name="@Model.Name" id="@Model.Id" class="datepickerfieldshadow" value="@val" />
<input type="text" name="@Model.Name" id="@(Model.Id)_1" class="datepickerfield" value="@val" @{if (Model.Mandatory) { <text> data-val="true" data-val-required="@Model.RequiredErrorMessage" </text> }} />

UmbracoDemo/Views/Partials/Forms/Fieldtypes/FieldType.DropDownList.cshtml
@model Umbraco.Forms.Mvc.Models.FieldViewModel
<select name="@Model.Name" id="@Model.Id"
@if (Model.Mandatory){<text> data-val="true" data-val-required="@Model.RequiredErrorMessage"</text>}
>
    <option value=""></option>
    @foreach (var pv in Model.PreValues)
    {
        <option value="@pv.Value" 
        @if (Model.ContainsValue(pv.Value))
        {<text>selected="selected"</text>}
        >@pv.Value</option>
    }
</select>

UmbracoDemo/Views/Partials/Forms/Fieldtypes/FieldType.FileUpload.cshtml
@using Umbraco.Web
@model Umbraco.Forms.Mvc.Models.FieldViewModel

<input type="file" name="@Model.Name" id="@Model.Id" multiple
@if(Model.Mandatory){<text> data-val="true" data-val-required="@Model.RequiredErrorMessage"</text>} />

@if (Model.Values != null && Model.Values.Any())
{
    <p>
        <strong>Current File/s:</strong><br/>
        @foreach (Dictionary<string, string> dictionaryObject in Model.Values)
        {
            @*
            The model.values contains a list of dictionary objects with a single item
            With the key being the full path to the file
            And the value being the filename
            *@
            if (dictionaryObject.Count > 0)
            {
                var fileInfo = dictionaryObject.First();
                <a href="@fileInfo.Key" target="_blank">@fileInfo.Value</a><br/>
                <input type="hidden" name="@(Model.Name)_file_@(fileInfo.Value)" value="@fileInfo.Key" />
            }
        }
    </p>
}

UmbracoDemo/Views/Partials/Forms/Fieldtypes/FieldType.HiddenField.cshtml
@model Umbraco.Forms.Mvc.Models.FieldViewModel
<input type="hidden" name="@Model.Name" id="@Model.Id" class="hidden" value="@Model.ValueAsHtmlString"/>

UmbracoDemo/Views/Partials/Forms/Fieldtypes/FieldType.PasswordField.cshtml
@model Umbraco.Forms.Mvc.Models.FieldViewModel
<input type="password" name="@Model.Name" id="@Model.Id" class="text" value="@Model.ValueAsHtmlString"
@{if(string.IsNullOrEmpty(Model.PlaceholderText) == false){<text>placeholder="@Model.PlaceholderText"</text>}}
@{if(Model.Mandatory || Model.Validate){<text>data-val="true"</text>}}
@{if (Model.Mandatory) {<text> data-val-required="@Model.RequiredErrorMessage"</text>}}
@{if (Model.Validate) {<text> data-val-regex="@Model.InvalidErrorMessage" data-regex="@Model.Regex"</text>}}
/>

UmbracoDemo/Views/Partials/Forms/Fieldtypes/FieldType.RadioButtonList.cshtml
@model Umbraco.Forms.Mvc.Models.FieldViewModel    
@{ var i = 0; }
   
<span class="radiobuttonlist" id="@Model.Id">
@foreach (Umbraco.Forms.Mvc.Models.PrevalueViewModel pv in Model.PreValues)  
{
    <input type="radio" name="@Model.Id" id="@string.Concat(Model.Id,"_",i)" value="@pv.Value" 
    @if (Model.Mandatory) {<text>data-val="true" data-val-requiredlist="@Model.RequiredErrorMessage"</text>}
    @if (Model.ContainsValue(pv.Value)){<text>checked="checked"</text>} />
    <label for="@string.Concat(Model.Id,"_",i)">@pv.Value</label>
    <br />
    
    i++;
}
</span>

UmbracoDemo/Views/Partials/Forms/Fieldtypes/FieldType.Text.cshtml
@model Umbraco.Forms.Mvc.Models.FieldViewModel
@using Umbraco.Forms.Core.Extensions

@{
    var settings = Model.AdditionalSettings;
    var hasCaption = (settings.ContainsKey("Caption") && !string.IsNullOrEmpty(settings["Caption"]));
    var hasBody = (settings.ContainsKey("BodyText") && !string.IsNullOrEmpty(settings["BodyText"]));
}

<div id="@Model.Id">
    @if (hasCaption)
    {
        <h2>@settings["Caption"].ParsePlaceHolders()</h2>
    }
    @if (hasBody)
    {
        <p>@Html.Raw(settings["BodyText"].ParsePlaceHolders().Replace(System.Environment.NewLine, "<br />"))</p>
    }
</div>

UmbracoDemo/Views/Partials/Forms/Fieldtypes/FieldType.Textarea.cshtml
@model Umbraco.Forms.Mvc.Models.FieldViewModel
<textarea name="@Model.Name" id="@Model.Id" rows="2" cols="20"
@{if(string.IsNullOrEmpty(Model.PlaceholderText) == false){<text>placeholder="@Model.PlaceholderText"</text>}}
@{if(Model.Mandatory || Model.Validate){<text>data-val="true"</text>}}
@{if (Model.Mandatory) {<text> data-val-required="@Model.RequiredErrorMessage"</text>}}
@{if (Model.Validate) {<text> data-val-regex="@Model.InvalidErrorMessage" data-regex="@Html.Raw(Model.Regex)"</text>}}
>@Model.ValueAsHtmlString</textarea>

UmbracoDemo/Views/Partials/Forms/Fieldtypes/FieldType.Textfield.cshtml
@model Umbraco.Forms.Mvc.Models.FieldViewModel
<input type="text" name="@Model.Name" id="@Model.Id" class="text" value="@Model.ValueAsHtmlString" maxlength="500"
@{if(string.IsNullOrEmpty(Model.PlaceholderText) == false){<text>placeholder="@Model.PlaceholderText"</text>}}
@{if(Model.Mandatory || Model.Validate){<text>data-val="true"</text>}}
@{if (Model.Mandatory) {<text> data-val-required="@Model.RequiredErrorMessage"</text>}}
@{if (Model.Validate) {<text> data-val-regex="@Model.InvalidErrorMessage" data-regex="@Html.Raw(Model.Regex)"</text>}}
/>

UmbracoDemo/Views/Partials/Forms/Fieldtypes/Fieldtype.Recaptcha.cshtml
@using System.Runtime.CompilerServices
@using Umbraco.Forms.Mvc.Helpers
@model Umbraco.Forms.Mvc.Models.FieldViewModel
@{
    var theme = "clean";
    if (Model.AdditionalSettings.Any(x => x.Key == "Theme"))
    {
        theme = Model.AdditionalSettings.FirstOrDefault(x => x.Key == "Theme").Value;
    }
}
@ReCaptchaHelper.ReCaptcha(theme)

UmbracoDemo/Views/Partials/Forms/Themes/bootstrap3-horizontal/Fieldtypes/FieldType.RadioButtonList.cshtml
@model Umbraco.Forms.Mvc.Models.FieldViewModel  
@using Umbraco.Forms.Mvc
  
@{ var i = 0; }


<div id="@Model.Id">
	
@foreach (Umbraco.Forms.Mvc.Models.PrevalueViewModel pv in Model.PreValues)  
{
	<div class="@Html.GetFormFieldClass(Model.FieldTypeName)  radio">
    	
		<label>
			<input type="radio" 
				name="@Model.Id" 
				id="@string.Concat(Model.Id,"_",i)" 
				value="@pv.Value" 
    			@if (Model.Mandatory) {<text>data-val="true" data-val-requiredlist="@Model.RequiredErrorMessage"</text>}
    			@if (Model.ContainsValue(pv.Value)){<text>checked="checked"</text>} />
    	
			@pv.Value
		</label>
    
	</div>
    
    i++;
}

</div>

UmbracoDemo/Views/Partials/Forms/Themes/default/Fieldtypes/FieldType.CheckBox.cshtml
@model Umbraco.Forms.Mvc.Models.FieldViewModel
@using Umbraco.Forms.Mvc

<input type="checkbox" name="@Model.Name" id="@Model.Id" 
       class="@Html.GetFormFieldClass(Model.FieldTypeName)" 

    @if(Model.Mandatory){<text>  data-val="true" data-val-requiredcb="@Model.RequiredErrorMessage"</text>}
    @if (Model.ContainsValue(true) || Model.ContainsValue("true") || Model.ContainsValue("on"))
    {<text>checked="checked"</text>}       
                                                                                                         
/>

UmbracoDemo/Views/Partials/Forms/Themes/default/Fieldtypes/FieldType.CheckBoxList.cshtml
@model Umbraco.Forms.Mvc.Models.FieldViewModel
@using Umbraco.Forms.Mvc

@{ var i = 0; }
          
<span class="checkboxlist" id="@Model.Id">
@foreach (Umbraco.Forms.Mvc.Models.PrevalueViewModel pv in Model.PreValues)  
{
    <input type="checkbox" 
           class="@Html.GetFormFieldClass(Model.FieldTypeName)" 
           name="@Model.Name" id="@string.Concat(Model.Id,"_",i)" value="@pv.Value" 
    @if (Model.Mandatory) {<text>data-val="true" data-val-requiredlist="@Model.RequiredErrorMessage"</text>}
    @if (Model.ContainsValue(pv.Value)){<text>checked="checked"</text>}/>
    
    <label for="@string.Concat(Model.Id,"_",i)">@pv.Value</label>
    <br />

    i++;
}
</span>

UmbracoDemo/Views/Partials/Forms/Themes/default/Fieldtypes/FieldType.DatePicker.cshtml
@model Umbraco.Forms.Mvc.Models.FieldViewModel       
@using Umbraco.Forms.Mvc
     
@{
    string val = string.Empty;
    if (Model.ValueAsObject != null && Model.ValueAsObject != "")
    {
        try
        {
            DateTime d;
            d = (DateTime) Model.ValueAsObject;
            val = d.ToShortDateString();
        }
        catch (Exception ex)
        {
            val = Model.ValueAsObject.ToString();
        }
    }
}

<input type="hidden" name="@Model.Name" id="@Model.Id" class="datepickerfieldshadow" value="@val" />
<input type="text" class="@Html.GetFormFieldClass(Model.FieldTypeName) text datepickerfield"  name="@Model.Name" id="@(Model.Id)_1" value="@val" @{if (Model.Mandatory) { <text> data-val="true" data-val-required="@Model.RequiredErrorMessage" </text> }} />

UmbracoDemo/Views/Partials/Forms/Themes/default/Fieldtypes/FieldType.DropDownList.cshtml
@model Umbraco.Forms.Mvc.Models.FieldViewModel
@using Umbraco.Forms.Mvc

<select class="@Html.GetFormFieldClass(Model.FieldTypeName)"  name="@Model.Name" id="@Model.Id"
@if (Model.Mandatory){<text> data-val="true" data-val-required="@Model.RequiredErrorMessage"</text>}
>
    <option value=""></option>
    @foreach (var pv in Model.PreValues)
    {
        <option value="@pv.Value" 
        @if (Model.ContainsValue(pv.Value))
        {<text>selected="selected"</text>}
        >@pv.Value</option>
    }
</select>

UmbracoDemo/Views/Partials/Forms/Themes/default/Fieldtypes/FieldType.HiddenField.cshtml
@model Umbraco.Forms.Mvc.Models.FieldViewModel
<input type="hidden" name="@Model.Name" id="@Model.Id" class="hidden" value="@Model.ValueAsHtmlString"/>

UmbracoDemo/Views/Partials/Forms/Themes/default/Fieldtypes/Fieldtype.Recaptcha.cshtml
@using System.Runtime.CompilerServices
@using Umbraco.Forms.Mvc.Helpers
@model Umbraco.Forms.Mvc.Models.FieldViewModel
@{
    var theme = "clean";
    if (Model.AdditionalSettings.Any(x => x.Key == "Theme"))
    {
        theme = Model.AdditionalSettings.FirstOrDefault(x => x.Key == "Theme").Value;
    }
}
@ReCaptchaHelper.ReCaptcha(theme)